language: node_js
node_js:
 - '0.10'
before_install:
 - gem install sass
 - gem install foundation
before_script:
 - npm install -g grunt-cli
 - npm install -g grunt
 - npm install -g bower
 - bower install