ProductBundle_tagged_full:
    pattern:   /product/tagged/{extraParams}/{currentpage}/{totalpageitems}/
    defaults:  { _controller: ProductBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
        totalpageitems: \d+
    
ProductBundle_tagged_noslash:
    pattern:   /product/tagged/{extraParams}/{currentpage}/{totalpageitems}
    defaults:  { _controller: ProductBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
        totalpageitems: \d+
    
ProductBundle_tagged_onlypage_slash:
    pattern:   /product/tagged/{extraParams}/{currentpage}/
    defaults:  { _controller: ProductBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
    
ProductBundle_tagged_onlypage:
    pattern:   /product/tagged/{extraParams}/{currentpage}
    defaults:  { _controller: ProductBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
    
ProductBundle_tagged_onlytag_slash:
    pattern:   /product/tagged/{extraParams}/
    defaults:  { _controller: ProductBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    
ProductBundle_tagged_onlytag:
    pattern:   /product/tagged/{extraParams}
    defaults:  { _controller: ProductBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    
ProductBundle_tagged_slash:
    pattern:   /product/tagged/
    defaults:  { _controller: ProductBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0} 
    
ProductBundle_tagged:
    pattern:   /product/tagged
    defaults:  { _controller: ProductBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    
ProductBundle_filtered:
    pattern:  /product/filterPages/
    defaults: { _controller: ProductBundle:Default:filterPages }

ProductBundle_page_full_slash:
    pattern:   /product/{alias}/{currentpage}/{totalpageitems}/{extraParams}/
    defaults:  { _controller: ProductBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
        totalpageitems: \d+
    
ProductBundle_page_full:
    pattern:   /product/{alias}/{currentpage}/{totalpageitems}/{extraParams}
    defaults:  { _controller: ProductBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
        totalpageitems: \d+

ProductBundle_page_only_pagin_slash:
    pattern:   /product/{alias}/{currentpage}/{totalpageitems}/
    defaults:  { _controller: ProductBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
    
ProductBundle_page_only_pagin:
    pattern:   /product/{alias}/{currentpage}/{totalpageitems}
    defaults:  { _controller: ProductBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
    
ProductBundle_page_only_page_slash:
    pattern:   /product/{alias}/{currentpage}/
    defaults:  { _controller: ProductBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0 }
    
ProductBundle_page_only_page:
    pattern:   /product/{alias}/{currentpage}
    defaults:  { _controller: ProductBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0 }
        
ProductBundle_page_normal_slash:
    pattern:   /product/{alias}/
    defaults:  { _controller: ProductBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0 }
        
ProductBundle_page_normal:
    pattern:   /product/{alias}
    defaults:  { _controller: ProductBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0 }
        
ProductBundle_home_slash:
    pattern:   /product/
    defaults:  { _controller: ProductBundle:Default:alias, alias: list, tags: all, currentpage: 0, totalpageitems: 0 }
        
ProductBundle_home:
    pattern:   /product
    defaults:  { _controller: ProductBundle:Default:alias, alias: list, tags: all, currentpage: 0, totalpageitems: 0 }
    
ProductBundle_showPage:
    pattern:  /product/showPage/{id}
    defaults: { _controller: ProductBundle:Default:showPage }

