PageBundle_tagged_full:
    pattern:   /tagged/{extraParams}/{currentpage}/{totalpageitems}/
    defaults:  { _controller: PageBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
        totalpageitems: \d+
    
PageBundle_tagged_noslash:
    pattern:   /tagged/{extraParams}/{currentpage}/{totalpageitems}
    defaults:  { _controller: PageBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
        totalpageitems: \d+
    
PageBundle_tagged_onlypage_slash:
    pattern:   /tagged/{extraParams}/{currentpage}/
    defaults:  { _controller: PageBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
    
PageBundle_tagged_onlypage:
    pattern:   /tagged/{extraParams}/{currentpage}
    defaults:  { _controller: PageBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
    
PageBundle_tagged_onlytag_slash:
    pattern:   /tagged/{extraParams}/
    defaults:  { _controller: PageBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    
PageBundle_tagged_onlytag:
    pattern:   /tagged/{extraParams}
    defaults:  { _controller: PageBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    
PageBundle_tagged_slash:
    pattern:   /tagged/
    defaults:  { _controller: PageBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0} 
    
PageBundle_tagged:
    pattern:   /tagged
    defaults:  { _controller: PageBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    
PageBundle_filtered:
    pattern:  /filterPages/
    defaults: { _controller: PageBundle:Default:filterPages }
    
PageBundle_sitemap:
    pattern:  /sitemap.{_format}
    defaults: { _controller: PageBundle:Default:sitemap, _format: xml}
    requirements:
        _format:  xml
    
PageBundle_sitemapxsl:
    pattern:  /sitemap.xsl
    defaults: { _controller: PageBundle:Default:sitemapxsl, _format: xml }
    
PageBundle_page_full:
    pattern:   /{alias}/{currentpage}/{totalpageitems}/{extraParams}/
    defaults:  { _controller: PageBundle:Default:alias, alias: index, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
        totalpageitems: \d+
    
PageBundle_page_noslash:
    pattern:   /{alias}/{currentpage}/{totalpageitems}/{extraParams}
    defaults:  { _controller: PageBundle:Default:alias, alias: index, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
        totalpageitems: \d+
    
PageBundle_page_onlypage_slash:
    pattern:   /{alias}/{currentpage}/{totalpageitems}/
    defaults:  { _controller: PageBundle:Default:alias, alias: index, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
    
PageBundle_page_onlypage:
    pattern:   /{alias}/{currentpage}/{totalpageitems}
    defaults:  { _controller: PageBundle:Default:alias, alias: index, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
    
PageBundle_page_onlypage_slash:
    pattern:   /{alias}/{currentpage}/
    defaults:  { _controller: PageBundle:Default:alias, alias: index, extraParams: all, currentpage: 0, totalpageitems: 0}
    
PageBundle_page_onlypage:
    pattern:   /{alias}/{currentpage}
    defaults:  { _controller: PageBundle:Default:alias, alias: index, extraParams: all, currentpage: 0, totalpageitems: 0}
    
PageBundle_page_slash:
    pattern:   /{alias}/
    defaults:  { _controller: PageBundle:Default:alias, alias: index, extraParams: all, currentpage: 0, totalpageitems: 0}
    
PageBundle_page:
    pattern:   /{alias}
    defaults:  { _controller: PageBundle:Default:alias, alias: index, extraParams: all, currentpage: 0, totalpageitems: 0}
    
PageBundle_index:
    pattern:   /
    defaults:  { _controller: PageBundle:Default:alias, alias: index, extraParams: all, currentpage: 0, totalpageitems: 0}   
    
PageBundle_showPage:
    pattern:  /showPage/{id}
    defaults: { _controller: PageBundle:Default:showPage }
    requirements:
        id: \d+