parameters:
    contenttypes:
        html:     Text/HTML
        image:    Image
        file:     File Attachment
        youtube:  YouTube Video
        slide:    Slide
        vimeo:    Vimeo Video
        contact:  Contact Form
    
    contentsizes:
        large-12:     100%
        large-3:      25%
        large-4:      33%
        large-6:      50%
        large-8:      66%
        large-9:      75%
        
    mediasizes:
        original:   Original
        small:      Small
        medium:     Medium
        big:        Big

services:
  page.twig.sort_by_attribute:
    class: BardisCMS\PageBundle\Twig\SortByAttribute
    tags:
      - {name: twig.extension }
            
  page.admin.form.type.contentblock:
    class: BardisCMS\PageBundle\Admin\Form\Type\ContentBlockType        
    arguments: [%contenttypes%, %contentsizes%, %mediasizes%]        
    tags:
      - { name: form.type, alias: contentblock }
            
  page.admin.form.type.contentblockcontent:
    class: BardisCMS\PageBundle\Admin\Form\Type\ContentBlockContentType        
    arguments: []        
    tags:
      - { name: form.type, alias: contentblockcontent }
            
  page.admin.form.type.contentblockcollection:
    class: BardisCMS\PageBundle\Admin\Form\Type\ContentBlockCollectionType        
    arguments: []        
    tags:
      - { name: form.type, alias: contentblockcollection }
            
  page.admin.form.type.contentimagecollection:
    class: BardisCMS\PageBundle\Admin\Form\Type\ContentImageCollectionType        
    arguments: []        
    tags:
      - { name: form.type, alias: contentimagecollection }
            
  page.admin.form.type.contentslide:
    class: BardisCMS\PageBundle\Admin\Form\Type\ContentSlideType        
    arguments: []        
    tags:
      - { name: form.type, alias: contentslide }
            
  page.admin.form.type.contentimage:
    class: BardisCMS\PageBundle\Admin\Form\Type\ContentImageType        
    arguments: []        
    tags:
      - { name: form.type, alias: contentimage }