parameters:
    contenttypes:
        html:     Text/HTML
        image:    Image
        file:     File Attachment
        youtube:  YouTube Video
        slide:    Slide
        vimeo:    Vimeo Video
        contact:  Contact Form
    
    contentsizes:
        large-12:     100%
        large-3:      25%
        large-4:      33%
        large-6:      50%
        large-8:      66%
        large-9:      75%
        
    mediasizes:
        original:   Original
        small:      Small
        medium:     Medium
        big:        Big

services: