RecipeBundle_tagged_full:
    pattern:   /recipe/tagged/{extraParams}/{currentpage}/{totalpageitems}/
    defaults:  { _controller: RecipeBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
        totalpageitems: \d+
    
RecipeBundle_tagged_noslash:
    pattern:   /recipe/tagged/{extraParams}/{currentpage}/{totalpageitems}
    defaults:  { _controller: RecipeBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
        totalpageitems: \d+
    
RecipeBundle_tagged_onlypage_slash:
    pattern:   /recipe/tagged/{extraParams}/{currentpage}/
    defaults:  { _controller: RecipeBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
    
RecipeBundle_tagged_onlypage:
    pattern:   /recipe/tagged/{extraParams}/{currentpage}
    defaults:  { _controller: RecipeBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
    
RecipeBundle_tagged_onlytag_slash:
    pattern:   /recipe/tagged/{extraParams}/
    defaults:  { _controller: RecipeBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    
RecipeBundle_tagged_onlytag:
    pattern:   /recipe/tagged/{extraParams}
    defaults:  { _controller: RecipeBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    
RecipeBundle_tagged_slash:
    pattern:   /recipe/tagged/
    defaults:  { _controller: RecipeBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0} 
    
RecipeBundle_tagged:
    pattern:   /recipe/tagged
    defaults:  { _controller: RecipeBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    
RecipeBundle_filtered:
    pattern:  /recipe/filterPages/
    defaults: { _controller: RecipeBundle:Default:filterPages }

RecipeBundle_page_full_slash:
    pattern:   /recipe/{alias}/{currentpage}/{totalpageitems}/{extraParams}/
    defaults:  { _controller: RecipeBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
        totalpageitems: \d+
    
RecipeBundle_page_full:
    pattern:   /recipe/{alias}/{currentpage}/{totalpageitems}/{extraParams}
    defaults:  { _controller: RecipeBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
        totalpageitems: \d+

RecipeBundle_page_only_pagin_slash:
    pattern:   /recipe/{alias}/{currentpage}/{totalpageitems}/
    defaults:  { _controller: RecipeBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
    
RecipeBundle_page_only_pagin:
    pattern:   /recipe/{alias}/{currentpage}/{totalpageitems}
    defaults:  { _controller: RecipeBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
    
RecipeBundle_page_only_page_slash:
    pattern:   /recipe/{alias}/{currentpage}/
    defaults:  { _controller: RecipeBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0 }
    
RecipeBundle_page_only_page:
    pattern:   /recipe/{alias}/{currentpage}
    defaults:  { _controller: RecipeBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0 }
        
RecipeBundle_page_normal_slash:
    pattern:   /recipe/{alias}/
    defaults:  { _controller: RecipeBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0 }
        
RecipeBundle_page_normal:
    pattern:   /recipe/{alias}
    defaults:  { _controller: RecipeBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0 }
        
RecipeBundle_home_slash:
    pattern:   /recipe/
    defaults:  { _controller: RecipeBundle:Default:alias, alias: list, tags: all, currentpage: 0, totalpageitems: 0 }
        
RecipeBundle_home:
    pattern:   /recipe
    defaults:  { _controller: RecipeBundle:Default:alias, alias: list, tags: all, currentpage: 0, totalpageitems: 0 }
    
RecipeBundle_showPage:
    pattern:  /recipe/showPage/{id}
    defaults: { _controller: RecipeBundle:Default:showPage }

