page:        
    loadservices: true
    
    pagetypes:
        one_columned:       One Column Page
        two_columned:       Two Column Page
        three_columned:     Three Column Page
        contact:            Contact Form Page
        category_page:      Category Page
        page_tag_list:			Filtered Results
        homepage:           Homepage
        sitemap:            Sitemap
    
    mediasizes:
        original:   Original
        small:      Small
        medium:     Medium
        big:        Big

content_block:        
    loadservices: true
    
    mediasizes:
        original:   Original
        small:      Small
        medium:     Medium
        big:        Big
        
    contenttypes:
        html:       Text/HTML
        image:      Image
        file:       File Attachment
        youtube:    YouTube Video
        slide:      Slide
        contact:    Contact Form
    
    contentsizes:
        large-12:     100%
        large-3:      25%
        large-4:      33%
        large-6:      50%
        large-8:      66%
        large-9:      75%
       
tag:        
    loadservices: true
    
    tagcategories:
        generic:       Generic Tags
        special:       Special Tags
       
category:        
    loadservices: false

menu:      
    actions:
        none:       None
        showPage:   Show Page
    
    menutypes:
        Page:					Page
        Blog:					Blog Page
        Spot:					Spot Page
        Destination:  Destination Page
        http:					External URL
        url:					Internal URL
        seperator:		Seperator
        
    menugroups:
        Main Menu:          Main Menu
        Small Footer Menu:  Small Footer Menu
        Footer Menu:        Footer Menu
    
    accessLevel:
        0:      Public
        1:      Authendicated
        2:      Administrator
    
    publishState:
        0:      Unpublished
        1:      Published
        
destination:        
    loadservices: true
    
    pagetypes:
        destination_article:         Destination Article
        destination_cat_page:        Destination Category Page
        destination_home:            Destination Homepage
    
    stylecolors:
        default:	Default
        green:		Green
        orange:		Orange
        pink:			Pink
        purple:		Purple
        red:			Red
    
    tagcategories:
        sports:		Sports

blog:        
    loadservices: true
    
    comments: true
    
    pagetypes:
        blog_article:         Blog Article
        blog_cat_page:        Blog Category Page
        blog_filtered_list:   Blog Filter Results
        blog_home:            Blog Homepage
    
    mediasizes:
        original:   Original
        small:      Small
        medium:     Medium
        big:        Big
        
        
spot:        
    loadservices: true
    
    pagetypes:
        spot_article:        Spot Page
        spot_home:           Spot Home
    
    filtercategories:
        amenities:      Amenities
        budget:					Budget
        experience:     Experience
        lifestyle:			Lifestyle
        season:         Season
        sea_state:      Sea State
        sport:					Sport
        style:          Style
        swell_length:   Swell Length
        wind_force:     Wind Force
        
comment:    
    loadservices: true
    
    commenttypes:
        Blog:       Blog Comments
        
#skeleton:        
#    loadservices: true
#    
#    pagetypes:
#        skeleton_article:         Skeleton Article
#        skeleton_filtered_list:   Skeleton Tag Results
#        skeleton_home:            Skeleton Homepage
#        category_page:            Skeleton Category Page
#   
#    mediasizes:
#        original:   Original
#        small:      Small
#        medium:     Medium
#        big:        Big