imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.xml }
    - { resource: sonata_cache.yml }
    - { resource: sonata_timeline.yml }
    - { resource: sonata_block.yml }
    - { resource: sonata_admin.yml }
    - { resource: sonata_media.yml }
    - { resource: bardiscms_bundles.yml }
    - { resource: tinymce.yml }
    - { resource: guzzle.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:         
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
      resources:
        - 'ContentBlockBundle:Form:fields.html.twig'
        - 'PageBundle:Form:fields.html.twig'
    
parameters:

    
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ PageBundle, BlogBundle, DestinationBundle, SpotBundle, FOSUserBundle ]
    java:           %javapath%
    
    filters:
        cssrewrite: ~
        #scssphp:
        #  apply_to: "\.scss$"
        #  import_paths: [ "%kernel.root_dir%/../web/bower_components/foundation/scss" ]
        #  compass: true
        scss:       ~
        yui_css:
            jar:    "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar.jar"
        yui_js:
            jar:    "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:       %database_driver%
        host:         %database_host%
        port:         %database_port%
        dbname:       %database_name%
        user:         %database_user%
        password:     %database_password%
        unix_socket:  %unix_socket%
        charset:      UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }



fos_user:
    db_driver:      orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User
    group:
        group_class:    Application\Sonata\UserBundle\Entity\Group
    from_email:
        address:        info@thegreekspots.co.uk
        sender_name:    TGS
    service:
        mailer:         fos_user.mailer.twig_swift
    registration:
        form:
            type:       registration
        confirmation:
            enabled:    true
            template:   FOSUserBundle:Registration:confirm_email.txt.twig

sonata_user:
    security_acl: true
    #sonata_user_impersonating:
    #    pattern: /
    #    defaults: { _controller: SonataPageBundle:Page:catchAll }
    impersonating_route: sonata_user_impersonating
    
    admin:
        user:
            class: Application\Sonata\UserBundle\Admin\Entity\BardisCMSUserAdmin