parameters:
#    skeleton.example.class: BardisCMS\SkeletonBundle\Example

services:
            
  recipe.form.recipefiltersform:
    class: BardisCMS\RecipeBundle\Form\RecipeFiltersFormType        
    arguments: ["@doctrine.orm.entity_manager"]        
    tags:
      - { name: form.type, alias: recipefiltersform }