SpotBundle_tagged_full:
    pattern:   /spots/{extraParams}/{currentpage}/{totalpageitems}/
    defaults:  { _controller: SpotBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
        totalpageitems: \d+
    
SpotBundle_tagged_noslash:
    pattern:   /spots/{extraParams}/{currentpage}/{totalpageitems}
    defaults:  { _controller: SpotBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
        totalpageitems: \d+
    
SpotBundle_tagged_onlypage_slash:
    pattern:   /spots/{extraParams}/{currentpage}/
    defaults:  { _controller: SpotBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
    
SpotBundle_tagged_onlypage:
    pattern:   /spots/{extraParams}/{currentpage}
    defaults:  { _controller: SpotBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
    
SpotBundle_tagged_onlytag_slash:
    pattern:   /spots/{extraParams}/
    defaults:  { _controller: SpotBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    
SpotBundle_tagged_onlytag:
    pattern:   /spots/{extraParams}
    defaults:  { _controller: SpotBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    
SpotBundle_tagged_slash:
    pattern:   /spots/
    defaults:  { _controller: SpotBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0} 
    
SpotBundle_tagged:
    pattern:   /spots
    defaults:  { _controller: SpotBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    
SpotBundle_filtered:
    pattern:  /filterSpots/
    defaults: { _controller: SpotBundle:Default:filterPages }

SpotBundle_page_full_slash:
    pattern:   /spot/{alias}/{currentpage}/{totalpageitems}/{extraParams}/
    defaults:  { _controller: SpotBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
        totalpageitems: \d+
    
SpotBundle_page_full:
    pattern:   /spot/{alias}/{currentpage}/{totalpageitems}/{extraParams}
    defaults:  { _controller: SpotBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
        totalpageitems: \d+

SpotBundle_page_only_pagin_slash:
    pattern:   /spot/{alias}/{currentpage}/{totalpageitems}/
    defaults:  { _controller: SpotBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
    
SpotBundle_page_only_pagin:
    pattern:   /spot/{alias}/{currentpage}/{totalpageitems}
    defaults:  { _controller: SpotBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
    
SpotBundle_page_only_page_slash:
    pattern:   /spot/{alias}/{currentpage}/
    defaults:  { _controller: SpotBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0 }
    
SpotBundle_page_only_page:
    pattern:   /spot/{alias}/{currentpage}
    defaults:  { _controller: SpotBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0 }
        
SpotBundle_page_normal_slash:
    pattern:   /spot/{alias}/
    defaults:  { _controller: SpotBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0 }
        
SpotBundle_page_normal:
    pattern:   /spot/{alias}
    defaults:  { _controller: SpotBundle:Default:alias, alias: list, extraParams: all, currentpage: 0, totalpageitems: 0 }
        
SpotBundle_home_slash:
    pattern:   /spot/
    defaults:  { _controller: SpotBundle:Default:alias, alias: list, tags: all, currentpage: 0, totalpageitems: 0 }
        
SpotBundle_home:
    pattern:   /spot
    defaults:  { _controller: SpotBundle:Default:alias, alias: list, tags: all, currentpage: 0, totalpageitems: 0 }
    
SpotBundle_showPage:
    pattern:  /spot/showPage/{id}
    defaults: { _controller: SpotBundle:Default:showPage }

