services:
      
  destination.tag_timestamp_listener:
    class: BardisCMS\DestinationBundle\Listener\TagTimestampListener
    tags:
        - { name: doctrine.event_listener, event: onFlush }
      
  destination.category_timestamp_listener:
    class: BardisCMS\DestinationBundle\Listener\CategoryTimestampListener
    tags:
        - { name: doctrine.event_listener, event: onFlush }