<?php

namespace Maynard\PageBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PageAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Maynard\PageBundle\Controller\PageAdminController();
        return $instance;
    }
}
