<?php

namespace Maynard\RecipeBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class RecipeAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Maynard\RecipeBundle\Controller\RecipeAdminController();
        return $instance;
    }
}
