<?php

namespace Maynard\SettingsBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SettingsAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Maynard\SettingsBundle\Controller\SettingsAdminController();
        return $instance;
    }
}
